In [1]:
marks = [60, 20, 70, 80]

In [2]:
hours = [6 ,2 ,7 ,8]

In [3]:
import numpy

In [4]:
marks = numpy.array(marks)

In [5]:
hours = numpy.array(hours)

In [6]:
marks

array([60, 20, 70, 80])

In [18]:
hours

array([6, 2, 7, 8])

In [21]:
hours = hours.reshape(-1, 1)

In [22]:
hours

array([[6],
       [2],
       [7],
       [8]])

In [25]:
jack_hours = [[5]] 

In [10]:
jack_marks = "?"

In [11]:
jack_marks

'?'

In [12]:
LinearRegression()

NameError: name 'LinearRegression' is not defined

In [15]:
from  sklearn.linear_model import LinearRegression

In [16]:
mind = LinearRegression()

In [23]:
mind.fit( hours , marks)

LinearRegression()

In [26]:
jack_marks = mind.predict(jack_hours)

In [27]:
jack_marks

array([50.])

In [30]:
mind.predict([[9]])

array([90.])